- id: arXiv:2502.04200
  title: "Characterizing Bugs in Login Processes of Android Applications: An Empirical Study"
  type: preprint
  description: "This paper is accepted by ICPC'25"
  tags:
    - login
    - empirical study
    - android


- id: arXiv:2501.07805
  title: "How Far are App Secrets from Being Stolen? A Case Study on Android"
  type: preprint
  description: "This paper is accepted by EMSE'25"
  tags:
    - android



- id: 10.1109/TSE.2025.3553383
  title: "Do Experts Agree About Smelly Infrastructure?"
  type: preprint
  tags:
    - anti-pattern


- id: arXiv:2408.01810
  title: "Demystifying Device-specific Compatibility Issues in Android Apps"
  type: paper
  description: "This paper is accepted by ICSME'24"
  buttons:
    - type: source
      text: Project
      link: https://zenodo.org/records/10964164
  tags:
    - android
    - device-specific
    - compatibility issue